/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BInputGroup: typeof import('bootstrap-vue-next')['BInputGroup']
    BInputGroupAppend: typeof import('bootstrap-vue-next')['BInputGroupAppend']
    Footer: typeof import('./src/components/globals/footer.vue')['default']
    Header: typeof import('./src/components/globals/header.vue')['default']
    HeaderFooter: typeof import('./src/components/globals/header-footer.vue')['default']
    HeaderLmenusSearchFooter: typeof import('./src/components/globals/header-lmenus-search-footer.vue')['default']
    HeaderMenus: typeof import('./src/components/globals/header-menus.vue')['default']
    Offers: typeof import('./src/components/offers/offers.vue')['default']
    Product: typeof import('./src/components/product/product.vue')['default']
    Product_detail: typeof import('./src/components/product/product_detail.vue')['default']
    Register: typeof import('./src/components/register/register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchOffert: typeof import('./src/components/searchProduct/searchOffert.vue')['default']
    SearchProduct: typeof import('./src/components/searchProduct/searchProduct.vue')['default']
    SearchTypeProduct: typeof import('./src/components/searchProduct/searchTypeProduct.vue')['default']
    Seller: typeof import('./src/components/register/seller/seller.vue')['default']
    SingIn: typeof import('./src/components/singIn/singIn.vue')['default']
  }
}
